# Generated by Django 4.2.3 on 2023-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SP', 'Спорт'), ('POL', 'Политика'), ('ECO', 'Экономика'), ('SOC', 'Общество')], default='SOC', max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('cover', models.ImageField(blank=True, default='image.jpg', upload_to='uploads/posts')),
            ],
        ),
    ]
